version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    working_directory:
    environment:
      HOST: 0.0.0.0
      NODE_ENV: developement
      secretession: lachristocratie
      type: service_account
      API_KEY: 'AIzaSyC38B7NGrKA5uz9w98-kBMbVp4qn1QCr34'
      AUTH_DOMAIN: 'cleanmyhouse-221915.firebaseapp.com'
      DB_URL: 'https://cleanmyhouse-221915.firebaseio.com'
      PROJECT_ID: 'cleanmyhouse-221915'
      STORAGE_BUCKET: 'cleanmyhouse-221915.appspot.com'
      MESSAGING_SENDER_ID: '207720984881'
      private_key_id: fa2b1dd029cd77eec650101a3316a9bb98122b0c
      private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCFXXzrpOeKzuKL\nwdvz1h48h8dWJsiIavXb/G4uyl37fV1pprowFaviicmlMmkk1Aakl+oDxnKIXmze\nZricNPU9JdrtxeRF2K9st6BpobTBbagi4OaAh2vIabQPmXlL2Fk6hiw+YQxhGl/k\nUOvq8WypZ29TKZBmMQ5aAV2YcbvmW+kj90ZW7xhT/l6mBTO7+3TRQB88+CjiMrUy\nIh4gFAwBcu0KxFKvmnOKBwFNbxp8YuBJdT/VWn8BOhu+4jf8FPdis9DyJCATRhuh\nIY7py+D2mgNQeEeIadLhjepyfiI3s9bB85Y/HiaN/XV4DROJ0hQbASBTEp24W1I8\nvae7UyQZAgMBAAECggEAAjCw2xOQOMDKLxesy6E1bnvo7wGNwz/FS5hvrsx2282b\ni/qi+5IIry7hQJmPn+rsoiWkiVrDiZ3KOjTNFjOlBIqiUzlUeYbkCqMIOxhxCqQt\nhmv4QbAcOeRbpzulJplvRI+jiKhv7Zu+tIznqc6qV5px1U5fcG4y9LW743pz1GF9\nG4QjLHoQslNk2ok4CRSXxqX0UVVi2kOA+QaJu0T2Zd6EcC4NGDra5O4INEzMsWJ7\nIxMG+c2QQ/po7ElpEHBnRY80Li0lLL4Lj9M6PvtSlUT1JcLXqB9gnGdyjJF13mp0\n0+1Cd2jrhpe5/XozDANoHcy8D2RZuJHd+5/a9/uMyQKBgQC6mfMmte99Os9E95oM\nllrMXI2EMoIPmMjjh8WiV531Syix14zN1NBtuDb4M6k4HlWRNJaLdYBOUF4if3s7\nyYDrkrdKyLLs/FtrJbbnhKy3LupwnTYs1ERKXCtl7Poj+YfR3o7E45bvxPy6qFGT\nt6V79fh5vHV8q/sEZE74NgdBKwKBgQC29v9WmON2tyqJ1GPhn0KJGoNH0zamLiUo\nmDJffXlLQAc4C0bYphC0QKL7KHwvUhV5zB18hNRUV5rb3Bp7c6xgSzfYigksY2t3\nbYBQ1X3u2uQ1sqYkVALV+lPiO5MLQJvsQ5o1KlYPsGA1dlJg6s2gFKhANmw0vccy\npaNHyVXlywKBgQCcl1bCVIk+aRzI/pPLHl3iA4VKu+wDVK64qhaDDs3irAjhfUaO\n8JlcieuvTAMksegSq7PuIlPi5HSqtJpg6M+EYSHp4xSr5XZ+Ky8biG48Z2WbzYJK\nCnOoh0JwDXc4u01sJD1hIrBmU8PWjCuxL7rylM7IsgtR7S0AWYEfsI9T8wKBgQCR\nKrxA2yFuqbmIjgmJlDDYUz7iGAT+KRK2eLtO5GD+gZi4sMnPT0NloPsvR1nwubHs\nZzTl/QXyvWdTFfm1BXw5ErUGi87ndyJnKWxrtlgq0WXL7SjBHh7545n2n8n1XZfZ\nB3IsyKBr5kcPZAfMecAYSQuNlyCXYBPSbXV1mZsbrQKBgQCloo0Rm0z5xp1XbrNZ\nVRxNsClgltA72mMWOpdp4u6NiIx0Ks9NZDP/BDblwuHlw+Ry3H6YjxwZTEhiRvW+\nabrIQoYh622qNIC5ZeXc0aohy1c2HAMu6VIfUFBh2/WwVTcZeUBas6COMFRG8oBD\nA6XRiGnFNSK5bVhNEF4TxA3QCQ==\n-----END PRIVATE KEY-----\n"
      client_email: firebase-adminsdk-k3mns@cleanmyhouse-221915.iam.gserviceaccount.com
      client_id: 109795484630692340483
      auth_uri: https://accounts.google.com/o/oauth2/auth
      token_uri: https://oauth2.googleapis.com/token
      auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
      client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-k3mns%40cleanmyhouse-221915.iam.gserviceaccount.com
      recaptcha_key: 6LfS0H4UAAAAAOhIxKJVdg1RF9nLePmxhA-5tF0S
      PUBLISHABLE_KEY: pk_test_pAIQcJtBPSf6kSAGUBvWJ00t
      SECRET_KEY: sk_test_bTJp9vsfYyPbtJstQdbWhuh1
      TITLE_APP: "Clean My House"
      NODE_TLS_REJECT_UNAUTHORIZED='0'
      PORT: 443
      uid: perenoel
      certpassword: direct11
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - run: # run coverage report
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-results.xml
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples